### ISSUE TITLE
failed job submission

### ISSUE THREAD

**Issue by webgisdeveloper** [SciGaP/eht_gateway#1]
it seems eht gateway can't connect to osg node right now

**Caused by: org.apache.airavata.agents.api.AgentException: java.net.UnknownHostException: EHTOSGConnect**

```
Failed to setup environment of task TASK_c8e4f25d-e6ea-4963-8a7c-800448e14e89

org.apache.airavata.helix.impl.task.TaskOnFailException: Error Code : cf3fb9f4-a279-479d-82ae-2d355346a42c, Task TASK_c8e4f25d-e6ea-4963-8a7c-800448e14e89 failed due to Failed to setup environment of task TASK_c8e4f25d-e6ea-4963-8a7c-800448e14e89, java.net.UnknownHostException: EHTOSGConnect
	at org.apache.airavata.helix.impl.task.AiravataTask.onFail(AiravataTask.java:146)
	at org.apache.airavata.helix.impl.task.env.EnvSetupTask.onRun(EnvSetupTask.java:58)
	at org.apache.airavata.helix.impl.task.AiravataTask.onRun(AiravataTask.java:437)
	at org.apache.airavata.helix.core.AbstractTask.run(AbstractTask.java:102)
	at org.apache.helix.task.TaskRunner.run(TaskRunner.java:71)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.airavata.agents.api.AgentException: java.net.UnknownHostException: EHTOSGConnect
	at org.apache.airavata.helix.adaptor.SSHJAgentAdaptor.createDirectory(SSHJAgentAdaptor.java:222)
	at org.apache.airavata.helix.impl.task.env.EnvSetupTask.onRun(EnvSetupTask.java:54)
	... 9 more
Caused by: java.net.UnknownHostException: EHTOSGConnect
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at net.schmizz.sshj.SocketClient.connect(SocketClient.java:126)
	at org.apache.airavata.helix.adaptor.PoolingSSHJClient.createNewSSHClient(PoolingSSHJClient.java:268)
	at org.apache.airavata.helix.adaptor.PoolingSSHJClient.newClientWithSessionValidation(PoolingSSHJClient.java:101)
	at org.apache.airavata.helix.adaptor.PoolingSSHJClient.leaseSSHClient(PoolingSSHJClient.java:141)
	at org.apache.airavata.helix.adaptor.PoolingSSHJClient.newSFTPClientWrapper(PoolingSSHJClient.java:322)
	at org.apache.airavata.helix.adaptor.SSHJAgentAdaptor.createDirectory(SSHJAgentAdaptor.java:212)
	... 10 more
```

**Comment by webgisdeveloper** [comment]
issue is fixed
